const assert = require('assert');
const { parseGcodeStats, parseDuration } = require('../src/gcode.js');

let pass = 0, fail = 0;
function check(name, fn) {
  try { fn(); console.log('  PASS  ' + name); pass++; }
  catch (e) { console.log('  FAIL  ' + name + '\n        ' + e.message); fail++; }
}

console.log('\nG-code parser tests\n');

// --- Format seen in the Printables "Big Box" listing (PrusaSlicer style) ---
check('parses PrusaSlicer-style header with real grams', () => {
  const g = `
; generated by PrusaSlicer 2.6.0
; filament used [mm] = 152984.38
; filament used [cm3] = 369.35
; total filament used [g] = 458.00
; total filament cost = 9.16
; estimated printing time (normal mode) = 1d 12h 57m 12s
`;
  const r = parseGcodeStats(g);
  assert.strictEqual(r.weightGrams, 458.00, 'weight');
  assert.strictEqual(r.weightSource, 'slicer_reported');
  assert.strictEqual(r.volumeCm3, 369.35);
  assert.strictEqual(r.timeSeconds, 133032, 'duration seconds, got ' + r.timeSeconds);
});

// --- Bambu Studio colon-delimited variant ---
check('parses Bambu-style colon-delimited header', () => {
  const g = `
; total filament weight [g] : 212.45
; total filament used [mm] : 70921.3
; total estimated time: 8h 12m 4s
`;
  const r = parseGcodeStats(g);
  assert.strictEqual(r.weightGrams, 212.45);
  assert.strictEqual(r.timeSeconds, 29524, 'got ' + r.timeSeconds);
});

// --- THE IMPORTANT ONE: slicer reports 0g because profile lacks density ---
check('recovers weight when slicer reports 0.00 g (missing density in profile)', () => {
  const g = `
; filament used [mm] = 14664.38
; filament used [cm3] = 35.27
; total filament used [g] = 0.00
; total filament cost = 0.00
; estimated printing time (normal mode) = 2h 36m 25s
`;
  const r = parseGcodeStats(g, { fallbackDensity: 1.24 });
  assert.ok(r.weightGrams > 0, 'must not return zero weight');
  assert.strictEqual(r.weightSource, 'volume_x_density');
  const expected = 35.27 * 1.24; // 43.73g
  assert.ok(Math.abs(r.weightGrams - expected) < 0.01, `got ${r.weightGrams}, expected ~${expected}`);
  assert.strictEqual(r.profileMissingDensity, true, 'should flag the bad profile');
});

// --- Length-only fallback, cross-checked against the 0.00298 g/mm figure ---
check('length-only fallback matches the 0.00298 g/mm reference for 1.75mm PLA', () => {
  const g = `; filament used [mm] = 10000.0`;
  const r = parseGcodeStats(g, { fallbackDensity: 1.24, fallbackDiameter: 1.75 });
  assert.strictEqual(r.weightSource, 'length_x_area_x_density');
  const perMm = r.weightGrams / 10000;
  assert.ok(Math.abs(perMm - 0.00298) < 0.00005,
    `got ${perMm.toFixed(6)} g/mm, spec sheet says ~0.00298`);
});

// --- Density embedded in the gcode should win over the fallback ---
check('prefers density declared in the G-code over the fallback', () => {
  const g = `
; filament_density = 1.27
; filament used [cm3] = 100.0
; total filament used [g] = 0.00
`;
  const r = parseGcodeStats(g, { fallbackDensity: 1.24 });
  assert.strictEqual(r.density, 1.27);
  assert.ok(Math.abs(r.weightGrams - 127.0) < 0.01, 'got ' + r.weightGrams);
});

check('returns nulls rather than throwing on unparseable input', () => {
  const r = parseGcodeStats('G1 X10 Y10\nG1 X20 Y20\n');
  assert.strictEqual(r.weightGrams, null);
  assert.strictEqual(r.weightSource, null);
});

check('duration parser handles assorted shapes', () => {
  assert.strictEqual(parseDuration('45m'), 2700);
  assert.strictEqual(parseDuration('2h 30m'), 9000);
  assert.strictEqual(parseDuration('1d'), 86400);
  assert.strictEqual(parseDuration('bogus'), null);
});

check('reads Bambu\'s two-durations-on-one-line summary as the total, not the sum', () => {
  // Verbatim from a real Bambu Studio slice. Both durations share a line, so
  // a pattern anchored to the start of the line never sees "total estimated
  // time", and one that captures to end-of-line swallows both numbers --
  // which parseDuration then adds together, roughly doubling the print time.
  const line = '; model printing time: 2h 56m 9s; total estimated time: 2h 56m 29s';
  const r = parseGcodeStats(line + '\n; total filament used [g] = 474.57\n');

  assert.strictEqual(r.timeSeconds, 2 * 3600 + 56 * 60 + 29,
    'should be the total estimated time (10589s), got ' + r.timeSeconds);
  assert.notStrictEqual(r.timeSeconds, 21158, 'must not sum the two durations');
  assert.strictEqual(r.weightGrams, 474.57);
});

check('prefers total estimated time over model printing time', () => {
  const r = parseGcodeStats('; model printing time: 1h; total estimated time: 3h\n');
  assert.strictEqual(r.timeSeconds, 10800, 'got ' + r.timeSeconds);
});

console.log(`\n${pass} passed, ${fail} failed\n`);
process.exit(fail === 0 ? 0 : 1);
